directory: /home/avery/share/music/bleep

paths:
  default: $albumartist - $album ($year) [$catalognum]/$track $title
  comp: Various artists/$album ($year) [$catalognum]/$track $title
  singleton: $artist - $title ($year) [$catalognum]

import:
  move: yes
  timid: yes

plugins:
  convert discogs embedart scrub web

convert:
  auto: yes
  delete_originals: yes

embedart:
  remove_art_file: yes

