alias scp-nyse="scp -r /home/nani/lab/NiceNYSE/* nani@mercurial:/web"
alias autostart="sh /home/nani/.config/openbox/autostart"
alias music="ncmpcpp"
alias mutracker="rtorrent -n -o import=~/.mutracker.rc"
alias whatcd="rtorrent -n -o import=~/.whatcd.rc"
alias weechat="weechat-curses"
alias muradio="mpd ~/.mpd/mutant.conf"
alias tar-gz="tar -xzvf"
alias compile="g++ -o"
