#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# ranger cd script
source ~/.zsh/ranger-cd

# environment
# kludges for HQM support [?]
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0

autoload -Uz compinit && compinit -i
