#!/bin/sh

bspc monitor LVDS1 -d dev web mus mov img
bspc monitor VGA1 -d dev2 web2 mus2 mov2 img2
bspc config border_width 5
bspc config window_gap 10
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config top_padding 20px
bspc config presel_border_color "#000000"
bspc config normal_border_color "#efefef"
bspc config focused_border_color "#000000"
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop=^3 follow=on floating=on
bspc rule -a pavucontrol floating=on focus=on
bspc rule -a feh floating=on
bspc rule -a run floating=on

sh ~/.config/bar/bspwm.sh &
xrandr --output LVDS1 --auto --output VGA1 --auto --right-of LVDS1 &
feh --bg-fill --no-xinerama ~/downloads/images/arch_bg.png &
pkill xflux &
xflux -l 49
